// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.2
// source: article/article.proto

package article

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ArticleClient is the client API for Article service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArticleClient interface {
	GetArticles(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ArticleListResponse, error)
	GetArticle(ctx context.Context, in *GetByIDReq, opts ...grpc.CallOption) (Article_GetArticleClient, error)
	IncreaseBuyCount(ctx context.Context, opts ...grpc.CallOption) (Article_IncreaseBuyCountClient, error)
}

type articleClient struct {
	cc grpc.ClientConnInterface
}

func NewArticleClient(cc grpc.ClientConnInterface) ArticleClient {
	return &articleClient{cc}
}

func (c *articleClient) GetArticles(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ArticleListResponse, error) {
	out := new(ArticleListResponse)
	err := c.cc.Invoke(ctx, "/Article/GetArticles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) GetArticle(ctx context.Context, in *GetByIDReq, opts ...grpc.CallOption) (Article_GetArticleClient, error) {
	stream, err := c.cc.NewStream(ctx, &Article_ServiceDesc.Streams[0], "/Article/GetArticle", opts...)
	if err != nil {
		return nil, err
	}
	x := &articleGetArticleClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Article_GetArticleClient interface {
	Recv() (*ArticleResponse, error)
	grpc.ClientStream
}

type articleGetArticleClient struct {
	grpc.ClientStream
}

func (x *articleGetArticleClient) Recv() (*ArticleResponse, error) {
	m := new(ArticleResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *articleClient) IncreaseBuyCount(ctx context.Context, opts ...grpc.CallOption) (Article_IncreaseBuyCountClient, error) {
	stream, err := c.cc.NewStream(ctx, &Article_ServiceDesc.Streams[1], "/Article/IncreaseBuyCount", opts...)
	if err != nil {
		return nil, err
	}
	x := &articleIncreaseBuyCountClient{stream}
	return x, nil
}

type Article_IncreaseBuyCountClient interface {
	Send(*GetByIDReq) error
	Recv() (*BuyCount, error)
	grpc.ClientStream
}

type articleIncreaseBuyCountClient struct {
	grpc.ClientStream
}

func (x *articleIncreaseBuyCountClient) Send(m *GetByIDReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *articleIncreaseBuyCountClient) Recv() (*BuyCount, error) {
	m := new(BuyCount)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ArticleServer is the server API for Article service.
// All implementations must embed UnimplementedArticleServer
// for forward compatibility
type ArticleServer interface {
	GetArticles(context.Context, *Empty) (*ArticleListResponse, error)
	GetArticle(*GetByIDReq, Article_GetArticleServer) error
	IncreaseBuyCount(Article_IncreaseBuyCountServer) error
	mustEmbedUnimplementedArticleServer()
}

// UnimplementedArticleServer must be embedded to have forward compatible implementations.
type UnimplementedArticleServer struct {
}

func (UnimplementedArticleServer) GetArticles(context.Context, *Empty) (*ArticleListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArticles not implemented")
}
func (UnimplementedArticleServer) GetArticle(*GetByIDReq, Article_GetArticleServer) error {
	return status.Errorf(codes.Unimplemented, "method GetArticle not implemented")
}
func (UnimplementedArticleServer) IncreaseBuyCount(Article_IncreaseBuyCountServer) error {
	return status.Errorf(codes.Unimplemented, "method IncreaseBuyCount not implemented")
}
func (UnimplementedArticleServer) mustEmbedUnimplementedArticleServer() {}

// UnsafeArticleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArticleServer will
// result in compilation errors.
type UnsafeArticleServer interface {
	mustEmbedUnimplementedArticleServer()
}

func RegisterArticleServer(s grpc.ServiceRegistrar, srv ArticleServer) {
	s.RegisterService(&Article_ServiceDesc, srv)
}

func _Article_GetArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).GetArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Article/GetArticles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).GetArticles(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_GetArticle_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetByIDReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ArticleServer).GetArticle(m, &articleGetArticleServer{stream})
}

type Article_GetArticleServer interface {
	Send(*ArticleResponse) error
	grpc.ServerStream
}

type articleGetArticleServer struct {
	grpc.ServerStream
}

func (x *articleGetArticleServer) Send(m *ArticleResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Article_IncreaseBuyCount_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ArticleServer).IncreaseBuyCount(&articleIncreaseBuyCountServer{stream})
}

type Article_IncreaseBuyCountServer interface {
	Send(*BuyCount) error
	Recv() (*GetByIDReq, error)
	grpc.ServerStream
}

type articleIncreaseBuyCountServer struct {
	grpc.ServerStream
}

func (x *articleIncreaseBuyCountServer) Send(m *BuyCount) error {
	return x.ServerStream.SendMsg(m)
}

func (x *articleIncreaseBuyCountServer) Recv() (*GetByIDReq, error) {
	m := new(GetByIDReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Article_ServiceDesc is the grpc.ServiceDesc for Article service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Article_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Article",
	HandlerType: (*ArticleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetArticles",
			Handler:    _Article_GetArticles_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetArticle",
			Handler:       _Article_GetArticle_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "IncreaseBuyCount",
			Handler:       _Article_IncreaseBuyCount_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "article/article.proto",
}
